In [119]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [120]:
df=pd.read_excel("../data/Telco_customer_churn.xlsx")

### Data Cleaning

In [121]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         7043 non-null   object
 1   Count              7043 non-null   int64
 2   Country            7043 non-null   object
 3   State              7043 non-null   object
 4   City               7043 non-null   object
 5   Zip Code           7043 non-null   int64
 6   Lat Long           7043 non-null   object
 7   Latitude           7043 non-null   float64
 8   Longitude          7043 non-null   float64
 9   Gender             7043 non-null   object
 10  Senior Citizen     7043 non-null   object
 11  Partner            7043 non-null   object
 12  Dependents         7043 non-null   object
 13  Tenure Months      7043 non-null   int64
 14  Phone Service      7043 non-null   object
 15  Multiple Lines     7043 non-null   object
 16  Internet Service   7043 non-null   object
 17  Online Security    7043 non-null   object
 18  Online Backup      7043 non-null   object
 19  Device Protection  7043 non-null   object
 20  Tech Support       7043 non-null   object
 21  Streaming TV       7043 non-null   object
 22  Streaming Movies   7043 non-null   object
 23  Contract           7043 non-null   object
 24  Paperless Billing  7043 non-null   object
 25  Payment Method     7043 non-null   object
 26  Monthly Charges    7043 non-null   float64
 27  Total Charges      7043 non-null   object
 28  Churn Label        7043 non-null   object
 29  Churn Value        7043 non-null   int64
 30  Churn Score        7043 non-null   int64
 31  CLTV               7043 non-null   int64
 32  Churn Reason       1869 non-null   object
dtypes: float64(3), int64(6), object(24)
memory usage: 1.8+ MB

In [122]:
df['Total Charges']

0        108.15
1        151.65
2         820.5
3       3046.05
4        5036.3
         ...
7038     1419.4
7039     1990.5
7040     7362.9
7041     346.45
7042     6844.5
Name: Total Charges, Length: 7043, dtype: object

In [123]:
df['Total Charges']=pd.to_numeric(df['Total Charges'],errors='coerce')
df['Total Charges']

0        108.15
1        151.65
2        820.50
3       3046.05
4       5036.30
         ...
7038    1419.40
7039    1990.50
7040    7362.90
7041     346.45
7042    6844.50
Name: Total Charges, Length: 7043, dtype: float64

In [124]:
df['Total Charges'].dtype

dtype('float64')

In [125]:
df['Total Charges'].isnull().sum()

11

In [126]:
df[df['Total Charges'].isnull()]['Tenure Months']

2234    0
2438    0
2568    0
2667    0
2856    0
4331    0
4687    0
5104    0
5719    0
6772    0
6840    0
Name: Tenure Months, dtype: int64

In [127]:
df[df['Total Charges'].isnull()]['Tenure Months'].shape

(11,)

In [128]:
df['Total Charges']=df['Total Charges'].fillna(0)

In [129]:
df['Total Charges'].isnull().sum()

0

In [130]:
df.shape

(7043, 33)

In [131]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         7043 non-null   object
 1   Count              7043 non-null   int64
 2   Country            7043 non-null   object
 3   State              7043 non-null   object
 4   City               7043 non-null   object
 5   Zip Code           7043 non-null   int64
 6   Lat Long           7043 non-null   object
 7   Latitude           7043 non-null   float64
 8   Longitude          7043 non-null   float64
 9   Gender             7043 non-null   object
 10  Senior Citizen     7043 non-null   object
 11  Partner            7043 non-null   object
 12  Dependents         7043 non-null   object
 13  Tenure Months      7043 non-null   int64
 14  Phone Service      7043 non-null   object
 15  Multiple Lines     7043 non-null   object
 16  Internet Service   7043 non-null   object
 17  Online Security    7043 non-null   object
 18  Online Backup      7043 non-null   object
 19  Device Protection  7043 non-null   object
 20  Tech Support       7043 non-null   object
 21  Streaming TV       7043 non-null   object
 22  Streaming Movies   7043 non-null   object
 23  Contract           7043 non-null   object
 24  Paperless Billing  7043 non-null   object
 25  Payment Method     7043 non-null   object
 26  Monthly Charges    7043 non-null   float64
 27  Total Charges      7043 non-null   float64
 28  Churn Label        7043 non-null   object
 29  Churn Value        7043 non-null   int64
 30  Churn Score        7043 non-null   int64
 31  CLTV               7043 non-null   int64
 32  Churn Reason       1869 non-null   object
dtypes: float64(4), int64(6), object(23)
memory usage: 1.8+ MB

In [132]:
drop_columns=['CustomerID','Count','Country','State','Zip Code','Lat Long','Latitude','Longitude','Churn Label','Churn Score','CLTV','Churn Reason']
df=df.drop(columns=drop_columns)

In [133]:
df.shape

(7043, 21)

In [134]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   City               7043 non-null   object
 1   Gender             7043 non-null   object
 2   Senior Citizen     7043 non-null   object
 3   Partner            7043 non-null   object
 4   Dependents         7043 non-null   object
 5   Tenure Months      7043 non-null   int64
 6   Phone Service      7043 non-null   object
 7   Multiple Lines     7043 non-null   object
 8   Internet Service   7043 non-null   object
 9   Online Security    7043 non-null   object
 10  Online Backup      7043 non-null   object
 11  Device Protection  7043 non-null   object
 12  Tech Support       7043 non-null   object
 13  Streaming TV       7043 non-null   object
 14  Streaming Movies   7043 non-null   object
 15  Contract           7043 non-null   object
 16  Paperless Billing  7043 non-null   object
 17  Payment Method     7043 non-null   object
 18  Monthly Charges    7043 non-null   float64
 19  Total Charges      7043 non-null   float64
 20  Churn Value        7043 non-null   int64
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [135]:
df['City'].unique()

array(['Los Angeles', 'Beverly Hills', 'Huntington Park', ..., 'Standish',
       'Tulelake', 'Olympic Valley'], dtype=object)

In [136]:
df['City'].value_counts()

City
Los Angeles       305
San Diego         150
San Jose          112
Sacramento        108
San Francisco     104
                 ...
Healdsburg          4
Jenner              4
Philo               4
Point Arena         4
Olympic Valley      4
Name: count, Length: 1129, dtype: int64

In [137]:
df_encoded=pd.get_dummies(df,drop_first=True)

In [138]:
df_encoded.head()

,Tenure Months,Monthly Charges,Total Charges,Churn Value,City_Acton,City_Adelanto,City_Adin,City_Agoura Hills,City_Aguanga,City_Ahwahnee,...,Streaming TV_No internet service,Streaming TV_Yes,Streaming Movies_No internet service,Streaming Movies_Yes,Contract_One year,Contract_Two year,Paperless Billing_Yes,Payment Method_Credit card (automatic),Payment Method_Electronic check,Payment Method_Mailed check
0,2,53.85,108.15,1,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,True
1,2,70.70,151.65,1,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,True,False
2,8,99.65,820.50,1,False,False,False,False,False,False,...,False,True,False,True,False,False,True,False,True,False
3,28,104.80,3046.05,1,False,False,False,False,False,False,...,False,True,False,True,False,False,True,False,True,False
4,49,103.70,5036.30,1,False,False,False,False,False,False,...,False,True,False,True,False,False,True,False,False,False

In [139]:
df_encoded.shape

(7043, 1159)

In [140]:
df=df.drop(columns=['City'])

In [141]:
df.shape

(7043, 20)

In [142]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Gender             7043 non-null   object
 1   Senior Citizen     7043 non-null   object
 2   Partner            7043 non-null   object
 3   Dependents         7043 non-null   object
 4   Tenure Months      7043 non-null   int64
 5   Phone Service      7043 non-null   object
 6   Multiple Lines     7043 non-null   object
 7   Internet Service   7043 non-null   object
 8   Online Security    7043 non-null   object
 9   Online Backup      7043 non-null   object
 10  Device Protection  7043 non-null   object
 11  Tech Support       7043 non-null   object
 12  Streaming TV       7043 non-null   object
 13  Streaming Movies   7043 non-null   object
 14  Contract           7043 non-null   object
 15  Paperless Billing  7043 non-null   object
 16  Payment Method     7043 non-null   object
 17  Monthly Charges    7043 non-null   float64
 18  Total Charges      7043 non-null   float64
 19  Churn Value        7043 non-null   int64
dtypes: float64(2), int64(2), object(16)
memory usage: 1.1+ MB

In [143]:
df_encoded=pd.get_dummies(df,drop_first=True)

In [144]:
df_encoded.shape

(7043, 31)

In [145]:
df_encoded

,Tenure Months,Monthly Charges,Total Charges,Churn Value,Gender_Male,Senior Citizen_Yes,Partner_Yes,Dependents_Yes,Phone Service_Yes,Multiple Lines_No phone service,...,Streaming TV_No internet service,Streaming TV_Yes,Streaming Movies_No internet service,Streaming Movies_Yes,Contract_One year,Contract_Two year,Paperless Billing_Yes,Payment Method_Credit card (automatic),Payment Method_Electronic check,Payment Method_Mailed check
0,2,53.85,108.15,1,True,False,False,False,True,False,...,False,False,False,False,False,False,True,False,False,True
1,2,70.70,151.65,1,False,False,False,True,True,False,...,False,False,False,False,False,False,True,False,True,False
2,8,99.65,820.50,1,False,False,False,True,True,False,...,False,True,False,True,False,False,True,False,True,False
3,28,104.80,3046.05,1,False,False,True,True,True,False,...,False,True,False,True,False,False,True,False,True,False
4,49,103.70,5036.30,1,True,False,False,True,True,False,...,False,True,False,True,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,72,21.15,1419.40,0,False,False,False,False,True,False,...,True,False,True,False,False,True,True,False,False,False
7039,24,84.80,1990.50,0,True,False,True,True,True,False,...,False,True,False,True,True,False,True,False,False,True
7040,72,103.20,7362.90,0,False,False,True,True,True,False,...,False,True,False,True,True,False,True,True,False,False
7041,11,29.60,346.45,0,False,False,True,True,False,True,...,False,False,False,False,False,False,True,False,True,False
7042,66,105.65,6844.50,0,True,False,False,False,True,False,...,False,True,False,True,False,True,True,False,False,False

In [146]:
X=df_encoded.drop('Churn Value',axis=1)
Y=df_encoded['Churn Value']

In [147]:
X.shape

(7043, 30)

In [148]:
Y.shape

(7043,)

In [149]:
print(X)

      Tenure Months  Monthly Charges  Total Charges  Gender_Male  \
0                 2            53.85         108.15         True
1                 2            70.70         151.65        False
2                 8            99.65         820.50        False
3                28           104.80        3046.05        False
4                49           103.70        5036.30         True
...             ...              ...            ...          ...
7038             72            21.15        1419.40        False
7039             24            84.80        1990.50         True
7040             72           103.20        7362.90        False
7041             11            29.60         346.45        False
7042             66           105.65        6844.50         True

      Senior Citizen_Yes  Partner_Yes  Dependents_Yes  Phone Service_Yes  \
0                  False        False           False               True
1                  False        False            True               True
2                  False        False            True               True
3                  False         True            True               True
4                  False        False            True               True
...                  ...          ...             ...                ...
7038               False        False           False               True
7039               False         True            True               True
7040               False         True            True               True
7041               False         True            True              False
7042               False        False           False               True

      Multiple Lines_No phone service  Multiple Lines_Yes  ...  \
0                               False               False  ...
1                               False               False  ...
2                               False                True  ...
3                               False                True  ...
4                               False                True  ...
...                               ...                 ...  ...
7038                            False               False  ...
7039                            False                True  ...
7040                            False                True  ...
7041                             True               False  ...
7042                            False               False  ...

      Streaming TV_No internet service  Streaming TV_Yes  \
0                                False             False
1                                False             False
2                                False              True
3                                False              True
4                                False              True
...                                ...               ...
7038                              True             False
7039                             False              True
7040                             False              True
7041                             False             False
7042                             False              True

      Streaming Movies_No internet service  Streaming Movies_Yes  \
0                                    False                 False
1                                    False                 False
2                                    False                  True
3                                    False                  True
4                                    False                  True
...                                    ...                   ...
7038                                  True                 False
7039                                 False                  True
7040                                 False                  True
7041                                 False                 False
7042                                 False                  True

      Contract_One year  Contract_Two year  Paperless Billing_Yes  \
0                 False              False                   True
1                 False              False                   True
2                 False              False                   True
3                 False              False                   True
4                 False              False                   True
...                 ...                ...                    ...
7038              False               True                   True
7039               True              False                   True
7040               True              False                   True
7041              False              False                   True
7042              False               True                   True

      Payment Method_Credit card (automatic)  Payment Method_Electronic check  \
0                                      False                            False
1                                      False                             True
2                                      False                             True
3                                      False                             True
4                                      False                            False
...                                      ...                              ...
7038                                   False                            False
7039                                   False                            False
7040                                    True                            False
7041                                   False                             True
7042                                   False                            False

      Payment Method_Mailed check
0                            True
1                           False
2                           False
3                           False
4                           False
...                           ...
7038                        False
7039                         True
7040                        False
7041                        False
7042                        False

[7043 rows x 30 columns]

In [150]:
print(Y)

0       1
1       1
2       1
3       1
4       1
       ..
7038    0
7039    0
7040    0
7041    0
7042    0
Name: Churn Value, Length: 7043, dtype: int64

In [151]:
X.to_csv("../data/X_clean.csv", index=False)
Y.to_csv("../data/Y_clean.csv", index=False)